version: '3.2'
services:
  app:
    build: .
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file: .env.local
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - ./node_modules
      - .:/app
